name: Code checks

on:
  pull_request:
    branches:
      - main   # ajusta si tu rama principal no es 'main'

jobs:
  lint:
    name: Flake8 Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run linting tests
        run: |
          flake8 src/ tests/

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint   # solo corre si lint pasa
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          pytest tests/ -v


